"""make raw_event_id unique

Revision ID: 313d25f83643
Revises: 7642c2329677
Create Date: 2025-09-09 21:34:14.430717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313d25f83643'
down_revision: Union[str, Sequence[str], None] = '7642c2329677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('raw_events_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'events', ['raw_events_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'raw_events_id')
    # ### end Alembic commands ###
