"""Add cgm_readings

Revision ID: 3a2d93882826
Revises: 6599b987feaa
Create Date: 2025-09-10 20:34:55.573409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2d93882826'
down_revision: Union[str, Sequence[str], None] = '6599b987feaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cgm_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cgm_reading', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('events_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cgm_readings')
    # ### end Alembic commands ###
