"""make event_id nonunique

Revision ID: 7642c2329677
Revises: 3fce426fc97b
Create Date: 2025-09-09 21:27:11.413285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7642c2329677'
down_revision: Union[str, Sequence[str], None] = '3fce426fc97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_event_id_key'), 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('events_event_id_key'), 'events', ['event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
