"""Add basal deliveries

Revision ID: 7b855b9a406c
Revises: 3a2d93882826
Create Date: 2025-09-11 19:54:33.701626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b855b9a406c'
down_revision: Union[str, Sequence[str], None] = '3a2d93882826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basal_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('profile_basal_rate', sa.Integer(), nullable=True),
    sa.Column('algorithm_basal_rate', sa.Integer(), nullable=True),
    sa.Column('temp_basal_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('events_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basal_deliveries')
    # ### end Alembic commands ###
